# Generated by Django 4.0 on 2022-01-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_alter_profile_image'),
        ('posts', '0015_threadmodel_messagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threaduser', to='socialapp.profile'),
        ),
    ]
