# Generated by Django 4.0 on 2022-01-06 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_alter_profile_image'),
        ('posts', '0016_alter_threadmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='threadmodel',
            name='has_unread',
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='receiver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_user', to='socialapp.profile'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_user', to='socialapp.profile'),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threadreceiver', to='socialapp.profile'),
        ),
    ]
